### ISSUE TITLE
useFirestoreCollection crash straight away on usage

### ISSUE THREAD

**Issue by ralcar** [FirebaseExtended/reactfire#216]
### Version info

**React:** 
0.0.0-experimental-ea6ed3dbb

**Firebase:**
7.9

**ReactFire:**
v2.0.0-rc.1

**Other (e.g. Node, browser, operating system) (if applicable):**
Node 10.15.1

### Test case

I want to load and then listen to changes to a collection in Firestore.

```jsx
import React from 'react';
import { useFirestore, useFirestoreCollection } from 'reactfire';

function SimpleTest() {
   const firestore = useFirestore;
   const ref = firestore().collection('productionTemplates');
   const productionTemplates = useFirestoreCollection(ref);

   return <h1>Hello World</h1>;
}
```

### Steps to reproduce

Add code above to any project

### Expected behavior

Expect to get a list from my selected collection back (no output in code above, but console logging it to inspect. Doesnt matter since it crashes)

### Actual behavior

Crash, pointing to missing canonicalId() on undefined.
Reactfire seems to expect _query to exist on the firestore query object, but it does not on inspection. In my environment it did have an object called "EP" that had the canonicalId function on it, tried to rebuild the npm package, switching from _query to EP and it loaded without error now.

<img width="519" alt="reactfire" src="https://user-images.githubusercontent.com/10072001/75035211-4614ce00-54af-11ea-9502-fab4ec1f6979.png">

**Comment by jhuleatt** [comment]
@jamesdaniels my guess is that this is due to the new proxy stuff?

**Comment by jamesdaniels** [comment]
Hmmm, interesting. Maybe this is a change to the internal API... or webpack mangling something. I’ll do some testing early next week. 

Could you try with Firebase 7.8?

**Comment by jamesdaniels** [comment]
Ah, yes just looked up the changelog. 7.9 ships with the minified Firestore, so we can’t count on that API... @jhuleatt could you look into a work around if you have time? Otherwise I’ll find time early next week. 

7.8 should be fine.

**Comment by jhuleatt** [comment]
Ohh, makes sense. I guess it isn't safe to call undocumented fields any more. I'll look into alternatives

**Comment by ToMissTheMarc** [comment]
Please let me know if you find any alternatives. I'm currently facing the same issue with firestoreCollection now.

**Comment by jhuleatt** [comment]
I'm having a tough time reproducing this - if anyone has time to create a StackBlitz/CodeSandbox demo that reproduces this, can you please comment a link in here?

**Comment by jhuleatt** [comment]
Looks like this was fixed in [7.9.1](https://firebase.google.com/support/release-notes/js#version_791_-_february_21_2020)

StackBlitz that shows it working now: https://stackblitz.com/fork/reactfire-issue-216

**Comment by ToMissTheMarc** [comment]
You're right... looks like firebase corrected this issue.

However, are you now seeing any issues with using useFirestoreCollection with a where clause when a variable has been updated in useState? For example, say I have an ownerId variable being used in a where clause and it's being set somewhere down in my code in a useEffect (setOwnerId). When the ownerId is finally set, the useFirestoreCollection isn't called again as it used to be:

`  const [ownerId, setOwnerId] = useState("")
  const obdsCol = firebase
    .firestore()
    .collection("obds")
    .where("ownerId", "==", ownerId);
  const obdsCollection = useFirestoreCollection(obdsCol);`

Perhaps it is just something in my code but what is odd is that obdsCollection is actually getting results only when a property on a document is update, like a query snapshot update. Anyway, could just be something on my end but it was working fine before this firestore change occurred.

**Comment by markmals** [comment]
Any guidance as to how to fix this issue? I'm still getting the `TypeError: Cannot read property 'canonicalId' of undefined` error from the `getHashFromFirestoreQuery` function. This is the code being called inside of a function component when ReactFire crashes:

```js
const restaurantsRef = useFirestore().collection("restaurants")
const restaurants = useFirestoreCollectionData(restaurantsRef)
```

I tried also using the

```js
const firebaseApp = useFirebaseApp()
const restaurantsRef = firebaseApp.firestore().collection("restaurants")
const restaurants = useFirestoreCollectionData(restaurantsRef)
```
configuration used in the StackBlitz, but I get a `firebaseApp.firestore is not a function` error when using that code. 

I'm on `"reactfire": "^2.0.1"` and `"firebase": "^7.9.3"` and I've run `yarn upgrade` on the project.

**Comment by banyan** [comment]
[7.9.1]( https://github.com/FirebaseExtended/reactfire/issues/216#issuecomment-590449622) works but 7.9.2, 7.9.3 and 7.10.0 don't work. Just change the version of reactfire on stackblits and it will be reproduced immediately.

**Comment by ToMissTheMarc** [comment]
I am on 7.9.1 of firebase and I am facing the issue again.

**Comment by jhuleatt** [comment]
reactfire 2.0.2 changed how we cache Firestore collection queries, and should fix this. I'll reopen this issue and keep it open until we confirm

**Comment by ToMissTheMarc** [comment]
Appears to be working so far.

**Comment by jhuleatt** [comment]
Cool, thanks for confirming. I'm going to close this - if someone else runs into a similar error on 2.0.2+, please open a new issue.
